### ISSUE TITLE
Unable to build websync

### ISSUE THREAD

**Issue by claybanger** [furier/websync#26] opened 2015-01-22 05:44 UTC
I've tried on multiple Ubuntu 14.04 servers to get websync running. Everything goes fine until executing 'gulp dist'.
```
~/websync$ gulp dist
[05:34:20] Using gulpfile ~/websync/gulpfile.js
[05:34:20] Starting 'clean'...
[05:34:20] Finished 'clean' after 6.94 ms
[05:34:20] Starting 'copy-server-to-dist'...
[05:34:20] Finished 'copy-server-to-dist' after 3.01 ms
[05:34:20] Starting 'browserify'...
[05:34:20] Finished 'browserify' after 3.18 ms
[05:34:20] Starting 'html'...
[05:34:20] Finished 'html' after 1.39 ms
[05:34:20] Starting 'css'...
[05:34:20] Finished 'css' after 4.49 ms
[05:34:20] Starting 'fonts'...
[05:34:20] Finished 'fonts' after 600 μs
[05:34:20] Starting 'imagemin'...
[05:34:20] Finished 'imagemin' after 1.67 ms
[05:34:20] Starting 'bower'...
[05:34:20] Finished 'bower' after 395 μs
[05:34:20] Starting 'build'...
[05:34:20] Finished 'build' after 1.53 ms
[05:34:20] Starting 'build-prod'...
[05:34:20] Finished 'build-prod' after 4.28 μs
[05:34:20] Starting 'dist'...
[05:34:20] Finished 'dist' after 4.69 μs
[05:34:20] gulp-imagemin: Minified 0 images (saved 0 B - 0%)

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Broken @import declaration of "toolkit.css"
```
Attempting to run websync gets this output: (which I'm presuming is related to above)
```
~/websync/dist$ node server.js 

module.js:340
    throw err;
          ^
Error: Cannot find module './lib/config/config'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/michael/websync/dist/server.js:13:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```
I've tried on existing machines and brand new installs.

**Comment by furier** [comment] 2015-01-22 21:32
Can you write up the exact steps, the exact commands you do for this to happen?

**Comment by claybanger** [comment] 2015-01-22 22:26
These were the steps I went through:
```
~/websync$ history
    1  sudo apt-get update
    2  sudo apt-get dist-upgrade
    3  sudo apt-get install git npm build-essential nodejs nodejs-legacy sshpass
    4  cd ~
    5  git clone https://github.com/furier/websync.git
    6  cd websync/
    7  npm install
    8  sudo npm install -g bower
    9  sudo npm install -g gulp
   10  bower install
   11  gulp dist
   12  history
```

I also tried a similar process on Debian which got the same error.

**Comment by furier** [comment] 2015-01-23 15:41
Im just curious if running the command `gulp` only for development mode will give the same error.
This is to narrow down if its an error with the production build process or if its common for both.

**Comment by claybanger** [comment] 2015-01-26 02:35
Looks like that provided the exact same error as before.
```
~/websync$ gulp
[02:34:18] Using gulpfile ~/websync/gulpfile.js
[02:34:18] Starting 'copy-server-to-dist'...
[02:34:18] Finished 'copy-server-to-dist' after 5.93 ms
[02:34:18] Starting 'server'...
[02:34:18] Finished 'server' after 8.31 ms
[02:34:18] Starting 'livereload'...
[02:34:18] Finished 'livereload' after 6.76 ms
[02:34:18] Starting 'watchify'...
[02:34:18] Starting 'html'...
[02:34:18] Finished 'html' after 1.48 ms
[02:34:18] Starting 'css'...
[02:34:18] Finished 'css' after 3.82 ms
[02:34:18] Starting 'fonts'...
[02:34:18] Finished 'fonts' after 1.18 ms
[02:34:18] Starting 'imagemin'...
[02:34:18] Finished 'imagemin' after 1.28 ms
[02:34:18] Starting 'bower'...
[02:34:18] Finished 'bower' after 955 μs
[02:34:18] Starting 'build'...
[02:34:18] Finished 'build' after 624 μs
[02:34:18] Live reload server listening on: 35729
[02:34:18] gulp-imagemin: Minified 0 images (saved 0 B - 0%)

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Broken @import declaration of "toolkit.css"
```

**Comment by furier** [comment] 2015-01-26 15:57
Strange, I have not encountered this problem before so Its kinda hard for me to reproduce i think. My guess its some version problem.

**Comment by michelange2008** [comment] 2015-02-17 06:19
Hello,
I encountered exactly the same problem (Debian Jessie).
Thanks for an idea to solve it
Michel

**Comment by furier** [comment] 2015-02-18 21:24
Please share the solution here or by making a pull request.

**Comment by michelange2008** [comment] 2015-02-19 05:15
Thanks,
But I have not yet the solution to fix the problem!

**Comment by melvincornelissen** [comment] 2015-03-04 20:23
Same problem here, different error. When using gulp I get the following error:

    stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
    Broken @import declaration of "toolkit.css"

When using gulp dist I get:

    events.js:72
        throw er; // Unhandled 'error' event
              ^
    Error: ENOTEMPTY, rmdir '/home/melvin/websync/dist/app/styles'

After emptying /home/melvin/websync/dist/app/styles I get:

    events.js:72
        throw er; // Unhandled 'error' event
              ^
    Error: ENOENT, stat '/home/melvin/websync/dist/app/fonts'

Permissions are fine... don't really understand where it's going wrong.

**Comment by furier** [comment] 2015-03-04 23:02
`ENOENT` means no file or directory to be found I belive.

You have followed the installation guide on the wiki?

In the gulp.js file try to delete the task having the issue with fonts, and get back to me.

**Comment by melvincornelissen** [comment] 2015-03-05 09:29
I did follow the installation guide on wiki, got it working in docker now though. 
I guess it means ERROR NO ENTRY. I will delete the task and try again. Thanks!

**Comment by cron410** [comment] 2015-03-12 22:39
For the life of me, cannot get this to run with Docker or with manual compiling. Please test this on a new ubuntu or debian install. Your development environment may be different than ours.

**Comment by Centurix** [comment] 2015-04-08 14:06
Stumbled across this problem, the @import problem is due to the mincss not bubbling up the @import to the top of the CSS files and then invalidating the CSS files. You can either move the @import and simplify, or use the bubbleCssImports option for mincss.

**Comment by Kwakpiper** [comment] 2015-04-14 08:00
Hi everybody,

I have got the same problem as claybanger, I have tried on Ubuntu 14.04, Ubuntu 12.04, Debian 7 and Debian 6. The line number of the error changes but the error type is the same.

Has somebody a solution to this problem ?
I don't know well node and I have'nt find it.

Thanks a lot

**Comment by furier** [comment] 2015-04-17 15:04
I have pushed a small commit where this issue should be resolved.

I just removed the css minification for now, will have to get back to this when I have more time. Hope in the near future. :)

**Comment by furier** [comment] 2015-04-20 11:53
Closing this bug as no replay has been given, assuming the bug has been fixed for other as well as myself.

**Comment by Kwakpiper** [comment] 2015-04-20 11:54
Thanks !

**Closed by furier** 2015-04-20 11:53 UTC
Labels: bug, WFR

**Comment by claybanger** [comment] 2015-04-21 01:03
websync now builds successfully. Thanks for sorting that out.

**Comment by sparklyballs** [comment] 2015-05-01 07:27
not building here,

[07:22:30] gulp-imagemin: Minified 0 images (saved 0 B - 0%)

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: ENOTEMPTY, rmdir '/home/websync/websync/dist/app/styles'

**Comment by furier** [comment] 2015-05-01 16:06
@sparklyballs try and manually delete the dist folder before running gulp again. Most times that's all that is needed when an error pops up.

**Comment by sparklyballs** [comment] 2015-05-01 16:58
i'm building a docker of this to eventually run on unraid.

i've found that by using this checkout

git checkout 27d58e540b3dcdd89d870e4bf1decadfece9ebcb

the build completes.
